project:
  type: website
  
website:
  title: "Mirindi Kabangu"
  
  navbar:
    left:
      - text: Projects
        href: projects/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: CV
    
  page-footer:
    left: |
      &copy; Copyright 2024, Mirindi Kabangu<br>
      Built with [Quarto](https://quarto.org/)
    right: |
      <i class="fas fa-envelope"></i> <a href="mailto:mkabangu@iu.edu">mkabangu@iu.edu</a><br>

format:
  html:
    theme: cosmo
    toc: true

editor: source

