project:
  type: website
  output-dir: docs
  
website:
  title: "Mirindi Kabangu"
  
  navbar:
    left:
      - text: Projects
        href: projects/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: CV
    
  page-footer:
    left: "&copy; Copyright 2025, Mirindi Kabangu<br>"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    toc: true

editor: source

