project:
  type: website
  output-dir: docs
  
website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/mirindi_
      - icon: github
        href: https://github.com/mkabangu/mirindikabangu
  page-footer:
    left: |
      "&copy; Copyright 2024, Mirindi Kabangu"<br>
      "Built with [Quarto](https://quarto.org/)"
    right: |
      <i class="fas fa-envelope"></i> <a href="mailto:mkabangu@iu.edu">mkabangu@iu.edu</a><br>

format:
  html:
    theme: cosmo
    toc: true

editor: source

